/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railway;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        login = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        tuname = new javax.swing.JTextField();
        tpass = new javax.swing.JPasswordField();
        logbutton = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        login.setText("LOGIN");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 188, 39));

        uname.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        uname.setText("USER ID");
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 228, 38));

        pass.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        pass.setText("PASSWORD");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 189, 35));

        tuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunameActionPerformed(evt);
            }
        });
        getContentPane().add(tuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 363, 38));
        getContentPane().add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 363, 35));

        logbutton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        logbutton.setText("LOGIN");
        logbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(logbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 116, 43));

        n2.setText("Create new account, register now");
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 224, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/pexels-pixabay-72594 (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 1240));

        pack();
    }// </editor-fold>                        

    private void logbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(tuname.getText().isEmpty()|| tpass.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter all details");
        }
        else
        {
        String n=tuname.getText();
        String p=tpass.getText();
         try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","root","123456");
            
            Statement stmt = con.createStatement();
            String sql1="SELECT userid,password FROM register where userid='"+n+"'";
            
            ResultSet rs = stmt.executeQuery(sql1);
            String uid = null,pd = null;
            while(rs.next())
            {
                
                 uid = rs.getString(1);
                 pd = rs.getString(2);
               
            }
            con.close();
           if (!tuname.getText().equals(uid) || !tpass.getText().equals(pd) )
            {
                JOptionPane.showMessageDialog(null,"Enter valid login details");
            }
            else
            {
                
                JOptionPane.showMessageDialog(null,"LOGIN SUCCESSFUL");
                Reserve r=new Reserve();
                r.loginid.setText(tuname.getText());
                r.setVisible(true);
                tuname.setText("");
                tpass.setText("");
                String sql2="insert into login values('"+uid+"','"+pd+"')";
                stmt.executeUpdate(sql2);
                
                
                
                
                
            }
            
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e){
            
        }
        }
    }                                         

    private void tunameActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        Register r =new Register();
        r.setVisible(true);
        dispose();
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logbutton;
    private javax.swing.JLabel login;
    private javax.swing.JButton n2;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField tpass;
    public javax.swing.JTextField tuname;
    private javax.swing.JLabel uname;
    // End of variables declaration                   
}
