/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railway;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
         setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        reglabel = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        pwd = new javax.swing.JLabel();
        cpwd = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tpwd = new javax.swing.JPasswordField();
        tcpwd = new javax.swing.JPasswordField();
        regbutton = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        tuserid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reglabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        reglabel.setText("REGISTERATION");
        getContentPane().add(reglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 315, 39));

        name.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        name.setForeground(new java.awt.Color(242, 242, 242));
        name.setText("NAME");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 211, 41));

        id.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        id.setForeground(new java.awt.Color(242, 242, 242));
        id.setText("USER ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 185, 57));

        pwd.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        pwd.setForeground(new java.awt.Color(242, 242, 242));
        pwd.setText("PASSWORD");
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 168, 37));

        cpwd.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        cpwd.setForeground(new java.awt.Color(242, 242, 242));
        cpwd.setText("CONFIRM PASSWORD");
        getContentPane().add(cpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 331, 32));
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 375, 41));
        getContentPane().add(tpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 375, 37));

        tcpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcpwdActionPerformed(evt);
            }
        });
        getContentPane().add(tcpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 375, 40));

        regbutton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        regbutton.setText("REGISTER");
        regbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(regbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 187, 60));

        n1.setText("Already registered ,login now");
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 278, -1));
        getContentPane().add(tuserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 375, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/pexels-dom-j-297836 (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 870));

        pack();
    }// </editor-fold>                        

    private void tcpwdActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void regbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
         if(tname.getText().isEmpty() ||tuserid .getText().isEmpty() || tpwd.getText().isEmpty() || tcpwd.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"ENTER ALL THE DETAILS");
        }
        else
        {
            String loginid=tuserid.getText();
            String uname=tname.getText();
            String pw1=tpwd.getText();
             String pw2=tcpwd.getText();
            String emailRegex="^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$";
            Pattern emailPat=Pattern.compile(emailRegex,Pattern.CASE_INSENSITIVE);
            Matcher matcher=emailPat.matcher(loginid);
            boolean b =matcher.find();
            if(b==true){
                if(tpwd.getText().equals(tcpwd.getText()))
                {
                   
                    try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","root","123456");
            
                    Statement stmt = con.createStatement();
                    String sql = "INSERT INTO REGISTER VALUES('"+loginid+"','"+pw2+"','"+uname+"')";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"REGISTERED SUCCESSFULLY");
                    con.close();
                    Login l = new Login();
                    l.setVisible(true);
                    dispose();
                    }
                    catch(Exception e){
                
                    }
                }
                else{
                
                    JOptionPane.showMessageDialog(null,"PASSWORD DOESN'T MATCH");
                    
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"ENTER VALID USERID");
            }
            
        }
        
        
                                      
    }                                         

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel cpwd;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton n1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pwd;
    private javax.swing.JButton regbutton;
    private javax.swing.JLabel reglabel;
    private javax.swing.JPasswordField tcpwd;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpwd;
    private javax.swing.JTextField tuserid;
    // End of variables declaration                   
}
