/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railway;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.UIManager.getString;
import java.lang.Long;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Reserve extends javax.swing.JFrame {

    /**
     * Creates new form Reserve
     */
    public Reserve() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tno = new javax.swing.JLabel();
        ttno = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        from = new javax.swing.JLabel();
        tfrom = new javax.swing.JTextField();
        depa = new javax.swing.JLabel();
        tdes = new javax.swing.JTextField();
        adult = new javax.swing.JLabel();
        child = new javax.swing.JLabel();
        seat = new javax.swing.JLabel();
        sleeper = new javax.swing.JLabel();
        adate = new javax.swing.JLabel();
        ddate = new javax.swing.JLabel();
        tadate = new javax.swing.JTextField();
        tddate = new javax.swing.JTextField();
        tadult = new javax.swing.JTextField();
        tchild = new javax.swing.JTextField();
        tseat = new javax.swing.JTextField();
        tsleep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        train = new javax.swing.JTable();
        detail = new javax.swing.JButton();
        loginid = new javax.swing.JLabel();
        reserve = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/pexels-pixabay-358167.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tno.setForeground(new java.awt.Color(242, 242, 242));
        tno.setText("Train Number");

        ttno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttnoMouseClicked(evt);
            }
        });

        name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(242, 242, 242));
        name.setText("Train Name");

        tname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tnameMouseClicked(evt);
            }
        });

        from.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        from.setForeground(new java.awt.Color(242, 242, 242));
        from.setText("Arrival");

        depa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        depa.setForeground(new java.awt.Color(242, 242, 242));
        depa.setText("Destination");

        adult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adult.setForeground(new java.awt.Color(242, 242, 242));
        adult.setText("Adults");

        child.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        child.setForeground(new java.awt.Color(242, 242, 242));
        child.setText("Children");

        seat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seat.setForeground(new java.awt.Color(242, 242, 242));
        seat.setText("Seater");

        sleeper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sleeper.setForeground(new java.awt.Color(242, 242, 242));
        sleeper.setText("Sleeper");

        adate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adate.setForeground(new java.awt.Color(242, 242, 242));
        adate.setText("Arrival Date");

        ddate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ddate.setForeground(new java.awt.Color(242, 242, 242));
        ddate.setText("Destination Date");

        tadult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tadultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(adate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(child, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(depa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(from, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ddate)
                            .addComponent(adult, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sleeper, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tddate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ttno)
                                .addComponent(tname)
                                .addComponent(tfrom)
                                .addComponent(tdes)
                                .addComponent(tadate, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                            .addComponent(tadult, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tchild, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tseat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tsleep, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tno)
                    .addComponent(ttno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from)
                    .addComponent(tfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depa)
                    .addComponent(tdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tadate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddate)
                    .addComponent(tddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adult)
                    .addComponent(tadult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(child)
                    .addComponent(tchild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat)
                    .addComponent(tseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sleeper)
                    .addComponent(tsleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, -1, -1));

        train.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Train number", "Train Name", "Arrival", "Destination "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        train.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(train);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 572, 300));

        detail.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        detail.setText("Train Details");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });
        getContentPane().add(detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, -1, 31));

        loginid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(loginid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 253, 28));

        reserve.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        reserve.setText("RESERVE");
        reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveActionPerformed(evt);
            }
        });
        getContentPane().add(reserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 186, 41));

        cancel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        cancel.setText("CANCELLATION AVAILABLE");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, -1, 41));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/pexels-pixabay-355966 (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1630, 1260));

        pack();
    }// </editor-fold>                        

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
             try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","root","123456");
                Statement stmt = con.createStatement();
                String sql = "select * from details";
                ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                String no=String.valueOf(rs.getInt(1));
                String trname=rs.getString(2);
                String arrival =rs.getString(3);
                String departure=rs.getString(4);
                String tbData[] ={no,trname,arrival,departure};
                 DefaultTableModel tblModel = (DefaultTableModel)train.getModel();
                 tblModel.addRow(tbData);
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(Reserve.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reserve.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         
       
       
    }                                      

    private void ttnoMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        
        
    }                                 

    private void tnameMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        String tno =ttno.getText();
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","root","123456");
                Statement stmt = con.createStatement();
                ResultSet rs=stmt.executeQuery("select * from details where trno='"+tno+"'");
                while(rs.next())
                {
                    tname.setText(rs.getString(2));
                    tfrom.setText(rs.getString(3));
                    tdes.setText(rs.getString(4));
                    tadate.setText(rs.getString(5));
                    tddate.setText(rs.getString(6));
                    
                }
                
                
        }
        catch(Exception e)
        {
        }
    }                                  

    private void tadultActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void reserveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
        if(ttno.getText().isEmpty()|| tadult.getText().isEmpty()||tchild.getText().isEmpty()||tseat.getText().isEmpty()||tsleep.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER ALL THE DETAILS");
        }
        else
        {
            String id=loginid.getText();
            String trainname=tname.getText();
            String arrival=tfrom.getText();
            String dep=tdes.getText();
            String a=tadate.getText();
            String d=tddate.getText();
        String trainno =ttno.getText();
        String adults=tadult.getText();
        String children=tchild.getText();
        String s=tseat.getText();
        String sl=tsleep.getText();
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","root","123456");
                    Statement stmt = con.createStatement();
                   int num1 = (int)((999999999-1)*Math.random()+1);
                    String pnr = String.format("%010d",num1);
                    String sql="insert into reserve values('"+id+"','"+trainno+"','"+trainname+"','"+arrival+"','"+dep+"','"+a+"','"+d+"','"+adults+"','"+children+"','"+s+"','"+sl+"','"+pnr+"')";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Your Reservation is Successful and PNR number generated: '"+pnr+"'");
                    Details details =new Details();
                    details.setVisible(true);
                }
                    
                    
                    
                    
            
            catch(HeadlessException | ClassNotFoundException | SQLException e){}
        }
    }                                       

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:

        Cancel c =new Cancel();
        c.setVisible(true);
        dispose();
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Reserve().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel adate;
    private javax.swing.JLabel adult;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel child;
    private javax.swing.JLabel ddate;
    private javax.swing.JLabel depa;
    private javax.swing.JButton detail;
    private javax.swing.JLabel from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel loginid;
    private javax.swing.JLabel name;
    private javax.swing.JButton reserve;
    private javax.swing.JLabel seat;
    private javax.swing.JLabel sleeper;
    private javax.swing.JTextField tadate;
    private javax.swing.JTextField tadult;
    private javax.swing.JTextField tchild;
    private javax.swing.JTextField tddate;
    private javax.swing.JTextField tdes;
    private javax.swing.JTextField tfrom;
    private javax.swing.JTextField tname;
    private javax.swing.JLabel tno;
    private javax.swing.JTable train;
    private javax.swing.JTextField tseat;
    private javax.swing.JTextField tsleep;
    private javax.swing.JTextField ttno;
    // End of variables declaration                   
}
